services:
  - type: web
    name: trading-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
